# Generated by Django 4.2.17 on 2025-09-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('api_version', models.CharField(blank=True, max_length=20, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_update', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='wholesale.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255)),
                ('airline_code', models.CharField(blank=True, max_length=50, null=True)),
                ('airline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_pdf', models.URLField(blank=True, null=True)),
                ('file_word', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('highlight', models.TextField(blank=True, null=True)),
                ('max_hotel_stars', models.IntegerField(blank=True, null=True)),
                ('min_hotel_stars', models.IntegerField(blank=True, null=True)),
                ('plane_meals', models.BooleanField(default=False)),
                ('total_meals', models.PositiveIntegerField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wholesale.country')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_tours', to='wholesale.provider')),
            ],
            options={
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bus', models.CharField(blank=True, max_length=20, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('airline_code', models.CharField(blank=True, max_length=50, null=True)),
                ('airline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('airport', models.CharField(blank=True, max_length=255, null=True)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('booked', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion', models.CharField(blank=True, max_length=10, null=True)),
                ('base_prices', models.JSONField(blank=True, null=True)),
                ('end_prices', models.JSONField(blank=True, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('com_agent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('com_agent_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('com_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('com_sale_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='wholesale.programtour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='wholesale.provider')),
            ],
            options={
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=255)),
                ('flight_no', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=255)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='wholesale.period')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='wholesale.programtour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='wholesale.provider')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='wholesale.provider'),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('day', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hotel', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_star', models.CharField(blank=True, max_length=10, null=True)),
                ('breakfast', models.BooleanField(default=False)),
                ('breakfast_desc', models.TextField(blank=True, null=True)),
                ('lunch', models.BooleanField(default=False)),
                ('lunch_desc', models.TextField(blank=True, null=True)),
                ('dinner', models.BooleanField(default=False)),
                ('dinner_desc', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='wholesale.programtour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='wholesale.provider')),
            ],
            options={
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('provider', 'provider_code')},
        ),
    ]
