# Generated by Django 4.2.17 on 2025-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='token',
            field=models.CharField(blank=True, help_text='API token for the provider, if required. Store securely.', max_length=512, null=True),
        ),
    ]
