# Generated by Django 4.2.17 on 2025-09-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_provider_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code (e.g., JOR, ESP, RUS)', max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized country name for deduplication (lowercase, trimmed)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['normalized_name'], name='wholesale_c_normali_c5c771_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_code'], name='wholesale_c_iso_cod_3caa3a_idx'),
        ),
    ]
