# Generated by Django 4.2.17 on 2025-10-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_country_iso_code_country_normalized_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawVendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Category ID if applicable', max_length=50)),
                ('external_id', models.CharField(help_text='Unique identifier from vendor API', max_length=255)),
                ('endpoint_type', models.CharField(default='departure', help_text='Type of data (tour, departure, etc.)', max_length=50)),
                ('raw_json', models.JSONField(help_text='Complete raw API response')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='wholesale.provider')),
            ],
            options={
                'verbose_name_plural': 'Raw Vendor Data',
                'indexes': [models.Index(fields=['provider', 'processed'], name='wholesale_r_provide_38ba25_idx'), models.Index(fields=['category', 'processed'], name='wholesale_r_categor_370927_idx')],
                'unique_together': {('provider', 'external_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text="API category ID (e.g., '59' for Europe)", max_length=50)),
                ('name', models.CharField(help_text='Category name in English', max_length=100)),
                ('name_local', models.CharField(blank=True, help_text='Category name in local language', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to sync this category')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority categories sync first')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('total_tours', models.IntegerField(default=0, help_text='Number of tours in this category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='wholesale.provider')),
            ],
            options={
                'verbose_name_plural': 'Provider Categories',
                'ordering': ['-priority', 'name'],
                'unique_together': {('provider', 'category_id')},
            },
        ),
    ]
