# Generated by Django 4.2.17 on 2026-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0006_remove_providermeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtour',
            name='data_quality_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='programtour',
            name='has_flights',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtour',
            name='has_full_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtour',
            name='has_itineraries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='programtour',
            index=models.Index(fields=['data_quality_score'], name='wholesale_p_data_qu_ea9a78_idx'),
        ),
        migrations.AddIndex(
            model_name='programtour',
            index=models.Index(fields=['has_flights', 'has_itineraries'], name='wholesale_p_has_fli_360033_idx'),
        ),
    ]
