# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wholesale', '0008_add_checkingroup_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtour',
            name='tour_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programtour',
            name='starting_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True,
                help_text='Minimum price across all periods'
            ),
        ),
        migrations.AddField(
            model_name='programtour',
            name='starting_price_air_ticket',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True,
                help_text='Minimum air ticket price across all periods'
            ),
        ),
        migrations.AddField(
            model_name='programtour',
            name='provider_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programtour',
            name='provider_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
