# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wholesale', '0009_add_tour_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon_url',
            field=models.URLField(
                blank=True, help_text='URL to country icon/flag image',
                null=True
            ),
        ),
    ]
