# Generated by Django 4.2.17 on 2026-01-15 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0010_add_country_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterEvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_code', models.CharField(max_length=50)),
                ('base_url', models.URLField()),
                ('sample_countries', models.JSONField(blank=True, null=True)),
                ('sample_tours', models.JSONField(blank=True, null=True)),
                ('sample_periods', models.JSONField(blank=True, null=True)),
                ('sample_flights', models.JSONField(blank=True, null=True)),
                ('sample_itineraries', models.JSONField(blank=True, null=True)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
                ('generated_service_code', models.TextField(blank=True, null=True)),
                ('generated_mapper_code', models.TextField(blank=True, null=True)),
                ('generated_normalizer_code', models.TextField(blank=True, null=True)),
                ('generated_command_code', models.TextField(blank=True, null=True)),
                ('generated_mappings_config', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('implemented', 'Implemented')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adapter Evaluation Session',
                'verbose_name_plural': 'Adapter Evaluation Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
