# Generated by Django 4.2.17 on 2026-01-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0011_adapterevaluationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterevaluationsession',
            name='auth_extra_config',
            field=models.JSONField(blank=True, help_text='Extra auth configuration (e.g., secret keys, param names)', null=True),
        ),
        migrations.AddField(
            model_name='adapterevaluationsession',
            name='auth_header_name',
            field=models.CharField(blank=True, help_text='Custom header name (for custom auth type)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adapterevaluationsession',
            name='auth_token',
            field=models.CharField(blank=True, help_text='API token, key, or password', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='adapterevaluationsession',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('api_token', 'API Token'), ('api_key_header', 'API Key (Header)'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth (Username/Password)'), ('email_param', 'Email (URL Parameter)'), ('custom', 'Custom')], default='none', help_text='Authentication method type', max_length=50),
        ),
        migrations.AddField(
            model_name='adapterevaluationsession',
            name='auth_username',
            field=models.CharField(blank=True, help_text='Username or email for authentication', max_length=255, null=True),
        ),
    ]
