# Generated by Django 4.2.17 on 2026-01-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0012_adapterevaluationsession_auth_extra_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
