# Generated by Django 4.2.17 on 2025-09-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tours.country')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('highlight', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('duration', models.CharField(max_length=50)),
                ('hotel_stars', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('DOMESTIC', 'Domestic Travel'), ('INTERNATIONAL', 'International Travel'), ('ADVENTURE', 'Adventure & Outdoor'), ('CRUISE', 'Cruise & Yacht'), ('BUSINESS', 'Business & MICE'), ('WELLNESS', 'Wellness & Medical'), ('CULTURAL', 'Cultural & Heritage'), ('LUXURY', 'Luxury Travel'), ('FAMILY', 'Family & Theme Parks')], default='DOMESTIC', max_length=20)),
                ('tour_type', models.CharField(choices=[('FLIGHT_ONLY', 'Flight Only'), ('HOTEL_ONLY', 'Hotel Only'), ('PACKAGE_TOUR', 'Package Tour'), ('PRIVATE_TOUR', 'Private Tour'), ('GROUP_TOUR', 'Group Tour'), ('BACKPACKING', 'Backpacking'), ('CRUISE_TOUR', 'Cruise Tour'), ('SELF_DRIVE', 'Self-Drive'), ('HONEYMOON', 'Honeymoon Package'), ('PILGRIMAGE', 'Religious & Pilgrimage'), ('FESTIVAL', 'Festival & Events'), ('SPORTS_TOUR', 'Sports & Adventure')], default='PACKAGE_TOUR', max_length=20)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.airline')),
                ('countries', models.ManyToManyField(to='tours.country')),
                ('locations', models.ManyToManyField(to='tours.location')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.operator')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_dates', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount applied to each TravelDate rate', max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('travel_dates', models.ManyToManyField(related_name='flash_sales', to='tours.traveldate')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='tours_flash_start_t_ce8526_idx'), models.Index(fields=['is_active'], name='tours_flash_is_acti_c52fcc_idx')],
            },
        ),
    ]
